# -*- coding: utf-8 -*-
# See LICENSE file for full copyright and licensing details
{
    'name': 'Tele Backend Enterprise Theme',
    'category': 'Themes/Backend',
    'version': '1.0.0.0',
    'summary' : '',
    'description': """ """,    
    'depends': ['web', 'web_enterprise', 'base_setup', 'portal', 'resource', 'tele_studio'], 
    'data': [
        'security/ir.model.access.csv',
        'data/backend_config_data.xml',
        'views/manifest.xml',
        'views/pwa_offline.xml',
        'views/backend_configurator_view.xml',
        'views/backend_configurator_template.xml',
        'views/res_config_setting.xml',
        'views/login_page_style.xml',
        'views/templates_inherit.xml',
        'views/ir_module_view.xml',
        'views/pwa_shortcuts_view.xml',
        'views/menuitems.xml',
    ],
    'demo': [
        'data/tele_default_images.xml',
    ],
    'assets': {
        'web.assets_qweb': [
            '/tele_theme_backend_ent/static/src/xml/ent_home_menu.xml',
            '/tele_theme_backend_ent/static/src/xml/web_inherit.xml',
            '/tele_theme_backend_ent/static/src/xml/menu.xml',
            '/tele_theme_backend_ent/static/src/xml/bookmark.xml',
            '/tele_theme_backend_ent/static/src/xml/base.xml',
            '/tele_theme_backend_ent/static/src/xml/view_button_icons.xml',
            # remove this bundle if you dont want to use studio
            '/tele_theme_backend_ent/static/src/xml/ent_studio.xml',
        ],
        'web.assets_backend': [
            # scss files
            "/tele_theme_backend_ent/static/src/scss/custom_varibles.scss",
            "/tele_theme_backend_ent/static/src/scss/font_size.scss",
            "/tele_theme_backend_ent/static/src/scss/font_icons.scss",
            "/tele_theme_backend_ent/static/src/scss/font-family.scss",
            
            "/tele_theme_backend_ent/static/src/scss/modal.scss",
            "/tele_theme_backend_ent/static/src/scss/search_modal.scss",
            "/tele_theme_backend_ent/static/src/scss/chat_window.scss",
            "/tele_theme_backend_ent/static/src/scss/common_view.scss",
            "/tele_theme_backend_ent/static/src/scss/discuss_style.scss",
            "/tele_theme_backend_ent/static/src/scss/list_view.scss",
            "/tele_theme_backend_ent/static/src/scss/kanban_view.scss",
            
            "/tele_theme_backend_ent/static/src/scss/form_view.scss",
            "/tele_theme_backend_ent/static/src/scss/form_chatter.scss",
            "/tele_theme_backend_ent/static/src/scss/tree_form_split_view.scss",

            "/tele_theme_backend_ent/static/src/scss/activity_view.scss",
            "/tele_theme_backend_ent/static/src/scss/pivot_view.scss",
            "/tele_theme_backend_ent/static/src/scss/graph_view.scss",
            "/tele_theme_backend_ent/static/src/scss/dashboards.scss",
            "/tele_theme_backend_ent/static/src/scss/calendear_view.scss",
            "/tele_theme_backend_ent/static/src/scss/setting_page.scss",
            "/tele_theme_backend_ent/static/src/scss/tab_styles.scss",
            "/tele_theme_backend_ent/static/src/scss/popup_styles.scss",
            "/tele_theme_backend_ent/static/src/scss/checkbox_styles.scss",
            "/tele_theme_backend_ent/static/src/scss/radio_styles.scss",
            "/tele_theme_backend_ent/static/src/scss/separator_styles.scss",
            "/tele_theme_backend_ent/static/src/scss/search_panel.scss",
            "/tele_theme_backend_ent/static/src/scss/loader.scss",
            "/tele_theme_backend_ent/static/src/scss/appdrawer.scss",
            "/tele_theme_backend_ent/static/src/scss/bookmarks.scss",
            "/tele_theme_backend_ent/static/src/scss/controlpannel.scss",
            "/tele_theme_backend_ent/static/src/scss/side_menu.scss",
            "/tele_theme_backend_ent/static/src/scss/responsive.scss",
            "/tele_theme_backend_ent/static/src/scss/notification.scss",
            "/tele_theme_backend_ent/static/src/scss/ent_home_menu.scss",
            "/tele_theme_backend_ent/static/src/scss/ent_burger_menu.scss",
            "/tele_theme_backend_ent/static/src/scss/ent_voip.scss",
            "/tele_theme_backend_ent/static/src/scss/studio.scss",

            # js files
            "/tele_theme_backend_ent/static/src/js/color_pallet.js",
            "/tele_theme_backend_ent/static/src/js/flip_min.js",
            "/tele_theme_backend_ent/static/src/js/menu.js",
            "/tele_theme_backend_ent/static/src/js/user_menu.js",
            "/tele_theme_backend_ent/static/src/js/apps_menu.js",
            "/tele_theme_backend_ent/static/src/js/SwitchCompanyMenu.js",
            "/tele_theme_backend_ent/static/src/js/form_view_renderer.js",
            "/tele_theme_backend_ent/static/src/js/list_view_renderer.js",
            "/tele_theme_backend_ent/static/src/js/TelePageTitle.js",
            "/tele_theme_backend_ent/static/src/js/pwebapp.js",
            "/tele_theme_backend_ent/static/src/js/iconpack_load.js",
            '/tele_theme_backend_ent/static/src/js/ent_home_menu.js',
            # open below comment for voip dialog design improve
            '/tele_theme_backend_ent/static/src/js/ent_voip.js',
        ],
        # remove this bundle if you dont want to use studio
        'tele_studio.studio_assets': [
            '/tele_theme_backend_ent/static/src/js/studio.js',
        ],
        'web.assets_frontend': [
            '/tele_theme_backend_ent/static/src/scss/loginpage.scss',
        ],
    },
    'sequence': 1,
    'application': True,
    'auto_install': True,
    'license': 'TPL-1',
}