version: '2'
services:
  web:
    image: telehub/tele:1.0
    depends_on:
      - db
    ports:
      - "9000:9000"
      - "8071:8071"
      - "8072:8072"
    volumes:
      - ./config:/etc/tele
      - ./applets:/mnt/extra-applets
      - ./tele_applets:/mnt/tele-applets
      - ./develop_applets:/mnt/develop-applets
      - /var/run/docker.sock:/var/run/docker.sock:ro
  db:
    image: postgres:14.0
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=telepwd
      - POSTGRES_USER=tele
   
#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"