# -*- coding: utf-8 -*-
{
    "name": "Theme Backend Theme",
    "summary": "Backend theme, Responsive theme, Fullu customizable theme, Material backend theme",
    "version": "1.0.1",
    "category": "Themes/Backend",
    "license": "TPL-1", 
    "depends": ["web", "mail"],   
    "data": [
        "views/res_users.xml", 
        "views/web.xml",
        "views/tele_theme_setting.xml",
        "security/ir.model.access.csv",
        "data/tele_theme_data.xml",
        ],
    "assets": {
        "web.assets_frontend": [
            "/tele_backend_theme/static/src/legacy/js/website_apps_menu.js",
            "/tele_backend_theme/static/src/legacy/scss/website_apps_menu.scss",
            "/tele_backend_theme/static/src/scss/login.scss",
        ],
        "web.assets_backend": [
            "/tele_backend_theme/static/src/scss/tele_theme_variables.scss",             
            "/tele_backend_theme/static/src/legacy/scss/tele_backend_theme.scss",
            "/tele_backend_theme/static/src/legacy/js/tele_backend_theme.js",
            "/tele_backend_theme/static/src/legacy/scss/kanban_view_mobile.scss",
            "/tele_backend_theme/static/src/legacy/js/kanban_renderer_mobile.js",
            "/tele_backend_theme/static/src/components/ui_context.esm.js",
            "/tele_backend_theme/static/src/components/apps_menu/apps_menu.scss",
            "/tele_backend_theme/static/src/components/apps_menu/apps_menu.esm.js",
            "/tele_backend_theme/static/src/components/navbar/main_navbar.scss",
            "/tele_backend_theme/static/src/components/control_panel/control_panel.scss",
            "/tele_backend_theme/static/src/components/control_panel/control_panel.esm.js",
            "/tele_backend_theme/static/src/components/search_panel/search_panel.scss",
            "/tele_backend_theme/static/src/components/search_panel/search_panel.esm.js",
            "/tele_backend_theme/static/src/components/attachment_viewer/attachment_viewer.scss",
            "/tele_backend_theme/static/src/components/attachment_viewer/attachment_viewer.esm.js",
            "/tele_backend_theme/static/src/components/hotkey/hotkey.scss",
            "/tele_backend_theme/static/src/scss/tele_setting.scss",
            "/tele_backend_theme/static/src/scss/style.scss",
            "/tele_backend_theme/static/src/scss/dark_mode.scss",
            "/tele_backend_theme/static/src/js/systray/systray_dark_mode_menu.js", 
        ],
        "web.assets_qweb": [
            "/tele_backend_theme/static/src/xml/dark_mode.xml",
            "/tele_backend_theme/static/src/legacy/xml/form_buttons.xml",
            "/tele_backend_theme/static/src/components/apps_menu/apps_menu.xml",
            "/tele_backend_theme/static/src/components/control_panel/control_panel.xml",
            "/tele_backend_theme/static/src/components/navbar/main_navbar.xml",
            "/tele_backend_theme/static/src/components/search_panel/search_panel.xml",
            "/tele_backend_theme/static/src/components/attachment_viewer/attachment_viewer.xml",
            "/tele_backend_theme/static/src/components/hotkey/hotkey.xml",    
            "/tele_backend_theme/static/src/xml/systray_dark_mode_menu.xml",
            "/tele_backend_theme/static/src/xml/pivot_view_inherit.xml",
        ],
        
    },
    'images': [
        '',
        
    ],
    'application': True,
    'auto_install': True,

}
